name: Lint
run-name: ${{ github.actor }} running lint action by ${{ github.event_name }}
on:
  push:
    branches: ['devel']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn
      - name: Lint
        run: yarn lint
