name: lint

on:
  push:
    branches: ['devel']
  pull_request:
    branches: ['master']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Lint
        run: |
          npm install -g yarn
          yarn
          yarn lint
