name: test
run-name: ${{ github.actor }} running lint action by ${{ github.event_name }}
on:
  push:
    branches: ['devel']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: package.json
          property: version
      - run: echo ${{steps.version.outputs.value}}

